### ISSUE TITLE
Repeated campaigns are not sent, because the time "Stop sending after" is not adjusted sensibly at the next repetition.

### ISSUE THREAD

**Issue by linuxlurak** [phpList/phplist3#911] opened 2022-11-27 20:05 UTC
I have a campaign using define('USE_REPETITION',1); in repetition mode. The first sending works without any problems. The next automatically created send seems to set the time "Embargoed Until" exactly to the time "Stop sending after". This then causes phplist to check the send at this time and then notice that it is not allowed to send. 

Possible solution: Here an additional field would have to be introduced, which adds the number of days/hours for the time "Stop sending after".

<img src="https://user-images.githubusercontent.com/3813355/204156569-38668b91-f7fc-4a97-9245-9bf5e2d1789c.png" width=50%>

Here is the excerpt from the eventlog (I'm not sure why the eventlog is displayed in german...)
<img src="https://user-images.githubusercontent.com/3813355/204156781-962ddbaa-9e37-4e79-bf37-f153afa7ad33.png" width=50%>

"Zeitüberschreitung beim Versand der Nachrichten, ist nach Versandzeit bis "
is translated from "Campaign sending timed out, is past date to process until" (see https://github.com/phpList/phplist3/blob/main/public_html/lists/admin/locale/de/phplist.po line 2260)

In the end the campaign is never sent.

**Comment by michield** [comment] 2022-11-27 21:04
What is your config for "DEFAULT_MESSAGEAGE" ?

That determines what the new "stop sending after" will be set to.

https://github.com/phpList/phplist3/blob/main/public_html/lists/admin/connect.php#L2029

**Comment by linuxlurak** [comment] 2022-11-28 18:05
In lists/config/config.php no definition of DEFAULT_MESSAGEAGE exists.

In lists/config/config_extended.php there exists this definition:
`define('DEFAULT_MESSAGEAGE', 15768000);`

I guess config_extended is not included? Is there a default value of DEFAULT_MESSAGEAGE?

In https://resources.phplist.com/system/config/default_messageage the info about the connection of DEFAULT_MESSAGE, USE_REPETITION and "stop sending after" is missing.

For the sake of completeness, an excerpt from config_extended:
```
// Message Age. The Scheduling tab has an option to stop sending a message when it has reached a certain date.
// This can be used to avoid the campaign going out, eg when an event has already taken place.
// This value defaults to the moment of creating the campaign + the number of seconds set here.
// phpList will mark the campaign as sent, when this date has been reached
// 15768000 is about 6 months, but other useful values can be
// 2592000 - 30 days
// 604800 - a week.
// 86400 - a day
define('DEFAULT_MESSAGEAGE', 15768000);
```
I'll give it a try with define('DEFAULT_MESSAGEAGE', 604800);.

Thanks @michield

**Comment by michield** [comment] 2022-11-28 22:12
If you didn't define it, it gets defaulted here: https://github.com/phpList/phplist3/blob/main/public_html/lists/admin/init.php#L599

So, it still seems odd. Let me know when you find the cause of this.

**Comment by linuxlurak** [comment] 2022-12-04 20:42
The mail dispatch has not worked up to and including today. I now suspect that it is a timeout problem. For sending mail I read a web page on the same server, which takes around 15 seconds. There must be a DNS problem here somewhere. I have now with a separate cron job and read out with curl the page in advance and pass it to phplist. 

Since then all phplist pages also load within about a second, before everything took 10 seconds to load for sure.

is there a timeout parameter for curl in the phplist settings?

this is of course rather symptom-fighting (exactly the same as my solution with a separate curl-cron job)... i know.

Translated with www.DeepL.com/Translator (free version)

**Comment by linuxlurak** [comment] 2022-12-11 08:11
It looks like this was a false alarm. The messages are sent properly, the problem was a timeout condition. In this case the URL resolution took about 15 seconds (you can check the duration for example with this command: `time wget -O /dev/null *URL.TLD*`). These 15 seconds were already enough to get the scripts out of step.

**Comment by linuxlurak** [comment] 2022-12-18 18:29
And again it failed... The mails were sent last week (weekly newsletter cycle), this morning it failed again. This is the event log of the test list:
![image](https://user-images.githubusercontent.com/3813355/208313059-c28e0143-6117-476c-b80c-1d6a4178427e.png)

Any idea how to get more info of whats going on? 

please reopen issue, thanks.

**Comment by linuxlurak** [comment] 2022-12-18 18:31
I could modify the code if you guide me a little bit and give me ideas. ;)

**Comment by michield** [comment] 2022-12-21 19:18
If you want to set yourself up for local development, here's the guide. https://resources.phplist.com/develop/docker

We can see if this can be replicated.

**Comment by linuxlurak** [comment] 2023-01-01 17:00
The campaign was not sent again:
![image](https://user-images.githubusercontent.com/3813355/210178823-a06717ee-10b5-41fc-91fe-7abf1eea71a9.png)




> If you want to set yourself up for local development, here's the guide. https://resources.phplist.com/develop/docker
> 
> We can see if this can be replicated.

Is there a difference in debugging using the dev docker version of phplist? I can modify the installation directly I guess.

**Comment by linuxlurak** [comment] 2023-01-01 19:35
I modified this line https://github.com/phpList/phplist3/blob/main/public_html/lists/admin/actions/processqueue.php#L976 
form   `$secondsTogo = $finishSendingBefore - time();`
to   `$secondsTogo = $finishSendingBefore - time() + 300;`

What do you think of this?

Just to be sure the routine wont stop because secondsTogo zeroed out. I send only 7 mails and that from a static website, all this is done within a few seconds if it works (and it always works the first time you enter the campaign).  +300 seconds should be more than enough.

Somehow it no longer works after a week... Previously I tested it in repeat mode with hourly cycle during a day and everything worked.

**Comment by michield** [comment] 2023-01-08 16:17
If you can push that change in a Pull Request, we can switch to your branch and try it out. That's the quickest way to review things. 

If you do so, can you also make sure to sign the [CLA](https://www.phplist.com/cla)?

**Comment by linuxlurak** [comment] 2023-01-08 18:21
Sure, if I get that far, I will. At the moment, the campaign is stuck with "still to process".

![image](https://user-images.githubusercontent.com/3813355/211212314-161ecef1-9e94-4a63-a0a9-1807a9f95d60.png)

I think this is new... Any ideas or hints what I can test?

**Comment by linuxlurak** [comment] 2023-01-15 17:24
Here is a new finding:

When I enter a campaign (daily recurrence) with a "Stop Sending After" date, the campaign is entered correctly and the "Stop Sending After" date is applied:

![image](https://user-images.githubusercontent.com/3813355/212556616-40429c68-28a1-4348-bb21-c329b0c1488e.png)


Once the campaign has been run and is re-entered using the repeat mechanism, the "Stop Sending After" date is set wrong.
![image](https://user-images.githubusercontent.com/3813355/212556607-c46da01e-a3d2-4543-872f-5f3422608698.png) 

Now the "Stop Sending After" date is before the date of lifting the embargo...

I did the same with an hourly campaign. This worked flawlessly. 

Daily or weekly recurrence does not work.

**Comment by linuxlurak** [comment] 2023-01-15 19:19
Ill test it with two weeks (1209600). So the weekly recurrence should work with the stop sending after date.

**Comment by michield** [comment] 2023-01-29 15:51
It must be something locally. I have this system https://monbiot.hosted.phplist.com/lists/ send out a daily email of the RSS feed from https://monbiot.com/feed/

That has worked without needing to change anything for more than a year.

**Comment by linuxlurak** [comment] 2023-01-29 17:16
I will observe my setting another week and then report back. I guess the problem was with DEFAULT_MESSAGEAGE. If it is set exactl to one week (604800=7d), every repetition after the first one will be older then allowed duration and the "stop sending date after" check will fail. 

Probably we should define DEFAULT_MESSAGEAGE to 8d (691200) as one week is one of the options to choose from in the repetition settings.

**Comment by michield** [comment] 2023-01-29 19:37
Ah, interesting. Yes, that makes sense. I don't think I ever tried weekly repeating emails, primarily daily ones. When you use the RSS plugin, it will try to send an email every day, but it won't if there's no content to send, so that works. Sounds like we could even make it higher, in case there's a monthly email to send.

**Comment by linuxlurak** [comment] 2023-02-05 07:56
After now 6 weeks of testing the sending of the weekly newsletter works without problems. With DEFAULT_MESSAGE set to 8d (691200) there is no unwanted send stop anymore.

Probable solution: DEFAULT_MESSAGE set to 8d (691200).

**Comment by michield** [comment] 2023-02-05 14:56
great, I've raised #932 to resolve that

**Comment by michield** [comment] 2023-02-05 17:27
I think we can close this now

**Closed by michield** 2023-02-05 17:27 UTC
