### ISSUE TITLE
upgrade failed Version phpList 3.6.3 

### ISSUE THREAD

**Issue by rotech1** [phpList/phplist3#772] opened 2021-05-25 22:57 UTC
Was at version 3.6.2.  Using updater: got to third step, then stalled with:

The update has been downloaded!
Downgrade is not supported.

**Comment by michield** [comment] 2021-05-26 07:57
interesting, thanks. We'll look into it.

**Comment by marianaballa** [comment] 2021-05-26 10:13
Until we have a fix for this, someone posted a "workaround" on the forum

https://discuss.phplist.org/t/phplist-3-6-3-updater-bug/7429

**Comment by bramley** [comment] 2021-05-27 06:45
@michield The top-level directory in the zip file downloaded from phplist `https://download.phplist.org/phplist.zip` has changed from "phplist" to "phplist-3.6.3". The updater code expects it to be "phplist", https://discuss.phplist.org/t/phplist-3-6-3-updater-bug/7429/2

**Comment by michield** [comment] 2021-05-27 07:37
Thanks. Slightly puzzling, as all of our zips always have had the phplist-x.y.z folder in it, so now I'm not sure how https://download.phplist.org/phplist.zip has not had that. I'll dig into it.

**Comment by michield** [comment] 2021-05-27 17:41
Yes, that's hard coded here: https://github.com/phpList/updater/blob/master/index.php#L764

**Comment by michield** [comment] 2021-05-28 07:42
I've temporarily marked the latest version to be 3.6.2, so that I can debug this.

**Comment by michield** [comment] 2021-06-05 09:47
We found the cause, and fixed it. Can you confirm it works now?

**Comment by bramley** [comment] 2021-06-06 07:31
Using the updater I was able to update successfully from 3.6.2 to 3.6.3.

**Comment by michield** [comment] 2021-06-06 16:57
Thanks for confirming

**Closed by michield** 2021-06-06 16:57 UTC
